/**
 * OpenFlights' `airports.dat` gives country *names*, not ISO 3166-1 alpha-2 codes, and
 * those names are occasionally inconsistent (both "Burma" and "Myanmar" appear; disputed
 * territories use non-standard labels like "Congo (Kinshasa)"). This is a hand-verified
 * mapping covering every country name observed in the dataset as of the 2014-era OpenFlights
 * snapshot, so route aggregation never silently drops an airport for lack of a lookup entry.
 *
 * Anything genuinely unmapped is reported by the caller (see `aggregate.ts`), not swallowed.
 */

export const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  'United States': 'US',
  Canada: 'CA',
  Australia: 'AU',
  Brazil: 'BR',
  Russia: 'RU',
  Germany: 'DE',
  China: 'CN',
  France: 'FR',
  'United Kingdom': 'GB',
  India: 'IN',
  Indonesia: 'ID',
  Japan: 'JP',
  'South Africa': 'ZA',
  Argentina: 'AR',
  Mexico: 'MX',
  Italy: 'IT',
  Iran: 'IR',
  Sweden: 'SE',
  Turkey: 'TR',
  Colombia: 'CO',
  Philippines: 'PH',
  Spain: 'ES',
  Norway: 'NO',
  'New Zealand': 'NZ',
  Venezuela: 'VE',
  Greenland: 'GL',
  Greece: 'GR',
  Pakistan: 'PK',
  Finland: 'FI',
  Thailand: 'TH',
  Chile: 'CL',
  'Saudi Arabia': 'SA',
  Algeria: 'DZ',
  'Congo (Kinshasa)': 'CD',
  'French Polynesia': 'PF',
  Madagascar: 'MG',
  Switzerland: 'CH',
  Peru: 'PE',
  Burma: 'MM',
  Myanmar: 'MM',
  Poland: 'PL',
  Malaysia: 'MY',
  Ukraine: 'UA',
  Ecuador: 'EC',
  'Papua New Guinea': 'PG',
  Kenya: 'KE',
  Portugal: 'PT',
  Bahamas: 'BS',
  Nepal: 'NP',
  Cuba: 'CU',
  Denmark: 'DK',
  'Costa Rica': 'CR',
  Ethiopia: 'ET',
  Tanzania: 'TZ',
  Vanuatu: 'VU',
  'South Korea': 'KR',
  Nigeria: 'NG',
  Netherlands: 'NL',
  Kazakhstan: 'KZ',
  Angola: 'AO',
  Taiwan: 'TW',
  Vietnam: 'VN',
  Belgium: 'BE',
  Egypt: 'EG',
  'Czech Republic': 'CZ',
  Bolivia: 'BO',
  'Solomon Islands': 'SB',
  Suriname: 'SR',
  Iceland: 'IS',
  Morocco: 'MA',
  Afghanistan: 'AF',
  Austria: 'AT',
  Romania: 'RO',
  Mozambique: 'MZ',
  Fiji: 'FJ',
  Libya: 'LY',
  Sudan: 'SD',
  Kiribati: 'KI',
  Namibia: 'NA',
  Ireland: 'IE',
  Israel: 'IL',
  'United Arab Emirates': 'AE',
  Botswana: 'BW',
  Zimbabwe: 'ZW',
  Hungary: 'HU',
  Iraq: 'IQ',
  Croatia: 'HR',
  'Dominican Republic': 'DO',
  Laos: 'LA',
  Tunisia: 'TN',
  Zambia: 'ZM',
  Gabon: 'GA',
  Bulgaria: 'BG',
  Nicaragua: 'NI',
  Panama: 'PA',
  Guyana: 'GY',
  Uzbekistan: 'UZ',
  Mongolia: 'MN',
  Uganda: 'UG',
  Honduras: 'HN',
  Belarus: 'BY',
  'Sri Lanka': 'LK',
  Senegal: 'SN',
  Mauritania: 'MR',
  'New Caledonia': 'NC',
  Uruguay: 'UY',
  Maldives: 'MV',
  Yemen: 'YE',
  Cameroon: 'CM',
  Malawi: 'MW',
  Guatemala: 'GT',
  'Puerto Rico': 'PR',
  Bangladesh: 'BD',
  Lithuania: 'LT',
  Estonia: 'EE',
  Mali: 'ML',
  Somalia: 'SO',
  Paraguay: 'PY',
  Kyrgyzstan: 'KG',
  Cambodia: 'KH',
  "Cote d'Ivoire": 'CI',
  Seychelles: 'SC',
  Guinea: 'GN',
  Slovakia: 'SK',
  'Cook Islands': 'CK',
  Oman: 'OM',
  'Marshall Islands': 'MH',
  Azerbaijan: 'AZ',
  Niger: 'NE',
  'Faroe Islands': 'FO',
  'Sierra Leone': 'SL',
  'Cape Verde': 'CV',
  Antarctica: 'AQ',
  Guadeloupe: 'GP',
  Latvia: 'LV',
  Ghana: 'GH',
  Chad: 'TD',
  Serbia: 'RS',
  'Turks and Caicos Islands': 'TC',
  Jamaica: 'JM',
  Haiti: 'HT',
  Tonga: 'TO',
  Jordan: 'JO',
  Syria: 'SY',
  'French Guiana': 'GF',
  Singapore: 'SG',
  'Congo (Brazzaville)': 'CG',
  Albania: 'AL',
  Cyprus: 'CY',
  Slovenia: 'SI',
  Moldova: 'MD',
  'Saint Vincent and the Grenadines': 'VC',
  Turkmenistan: 'TM',
  'North Korea': 'KP',
  Armenia: 'AM',
  Georgia: 'GE',
  Togo: 'TG',
  Comoros: 'KM',
  'Bosnia and Herzegovina': 'BA',
  Micronesia: 'FM',
  Tajikistan: 'TJ',
  Benin: 'BJ',
  'Equatorial Guinea': 'GQ',
  Reunion: 'RE',
  Lesotho: 'LS',
  'Guinea-Bissau': 'GW',
  Liberia: 'LR',
  Rwanda: 'RW',
  'South Sudan': 'SS',
  'El Salvador': 'SV',
  'Cayman Islands': 'KY',
  Belize: 'BZ',
  Samoa: 'WS',
  Kuwait: 'KW',
  Lebanon: 'LB',
  Qatar: 'QA',
  'Northern Mariana Islands': 'MP',
  'Virgin Islands': 'VI',
  'British Virgin Islands': 'VG',
  'Hong Kong': 'HK',
  Bhutan: 'BT',
  'East Timor': 'TL',
  Eritrea: 'ER',
  Djibouti: 'DJ',
  'Western Sahara': 'EH',
  'Burkina Faso': 'BF',
  Guernsey: 'GG',
  'Falkland Islands': 'FK',
  Swaziland: 'SZ',
  'Central African Republic': 'CF',
  Mauritius: 'MU',
  'Sao Tome and Principe': 'ST',
  Burundi: 'BI',
  'Saint Pierre and Miquelon': 'PM',
  Malta: 'MT',
  Macedonia: 'MK',
  Montenegro: 'ME',
  'Wallis and Futuna': 'WF',
  'American Samoa': 'AS',
  Bahrain: 'BH',
  Guam: 'GU',
  'Antigua and Barbuda': 'AG',
  Dominica: 'DM',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Trinidad and Tobago': 'TT',
  Brunei: 'BN',
  Svalbard: 'SJ',
  Jersey: 'JE',
  'Isle of Man': 'IM',
  Luxembourg: 'LU',
  'Saint Helena': 'SH',
  'British Indian Ocean Territory': 'IO',
  Mayotte: 'YT',
  Gambia: 'GM',
  Gibraltar: 'GI',
  'West Bank': 'PS',
  Palestine: 'PS',
  Palau: 'PW',
  Barbados: 'BB',
  Martinique: 'MQ',
  Grenada: 'GD',
  Aruba: 'AW',
  Anguilla: 'AI',
  Macau: 'MO',
  'Christmas Island': 'CX',
  'Norfolk Island': 'NF',
  Bermuda: 'BM',
  Nauru: 'NR',
  Tuvalu: 'TV',
  Montserrat: 'MS',
  Niue: 'NU',
  'Cocos (Keeling) Islands': 'CC',
  // US Minor Outlying Islands — no scheduled commercial routes of consequence, mapped for
  // completeness rather than left to swell the unmapped-name log every run.
  'Midway Islands': 'UM',
  'Wake Island': 'UM',
  'Johnston Atoll': 'UM',
  // Dissolved in 2010 into Curacao/Sint Maarten/the Caribbean Netherlands; OpenFlights never
  // updated its handful of airport rows. There is no single correct modern iso2 for it, so it
  // is deliberately left unmapped and reported rather than guessed.
  // 'Netherlands Antilles': intentionally absent.
};

/**
 * Display-name overrides for iso2 codes whose OpenFlights source string is outdated,
 * ambiguous, or awkward to show in the UI. Anything not listed here falls back to
 * whichever raw OpenFlights name mapped to that code.
 */
export const ISO2_DISPLAY_NAME_OVERRIDES: Record<string, string> = {
  MM: 'Myanmar',
  CD: 'DR Congo',
  CG: 'Congo',
  KR: 'South Korea',
  KP: 'North Korea',
  TL: 'Timor-Leste',
  MK: 'North Macedonia',
  SZ: 'Eswatini',
  CI: "Côte d'Ivoire",
  PS: 'Palestine',
};

export function mapCountryNameToIso2(rawName: string): string | undefined {
  return COUNTRY_NAME_TO_ISO2[rawName];
}

export function displayNameForIso2(iso2: string, fallbackRawName: string): string {
  return ISO2_DISPLAY_NAME_OVERRIDES[iso2] ?? fallbackRawName;
}
